const CONTROL_ACCESSOR_TOKEN = "__SmartMed_CONTROL_ACCESSOR_TOKEN";

const MODEL_MODIFIERS_TOKEN = "__SmartMed_MODEL_MODIFIERS_TOKEN";

const VALIDATION_ERRORS_TOKEN = "__SmartMed_VALIDATION_ERRORS_TOKEN";

const EVENT_TUNNEL_PROGRESS_TOKEN = "__SmartMed_EVENT_TUNNEL_PROGRESS_TOKEN";

const EVENT_TUNNEL_TOKEN = "__SmartMed_EVENT_TUNNEL_TOKEN";

const ACTIVE_ELEMENT_TOKEN = "__SmartMed_ACTIVE_ELEMENT_TOKEN";

const SELECTION_CHANGE_TOKEN = "__SmartMed_SELECTION_CHANGE_TOKEN";

export { ACTIVE_ELEMENT_TOKEN, CONTROL_ACCESSOR_TOKEN, EVENT_TUNNEL_PROGRESS_TOKEN, EVENT_TUNNEL_TOKEN, MODEL_MODIFIERS_TOKEN, SELECTION_CHANGE_TOKEN, VALIDATION_ERRORS_TOKEN };
