this.smartmed = this.smartmed || {};
this.smartmed.tokens = (function (exports) {
  'use strict';

  const CONTROL_ACCESSOR_TOKEN = "__SmartMed_CONTROL_ACCESSOR_TOKEN";

  const MODEL_MODIFIERS_TOKEN = "__SmartMed_MODEL_MODIFIERS_TOKEN";

  const VALIDATION_ERRORS_TOKEN = "__SmartMed_VALIDATION_ERRORS_TOKEN";

  const EVENT_TUNNEL_PROGRESS_TOKEN = "__SmartMed_EVENT_TUNNEL_PROGRESS_TOKEN";

  const EVENT_TUNNEL_TOKEN = "__SmartMed_EVENT_TUNNEL_TOKEN";

  const ACTIVE_ELEMENT_TOKEN = "__SmartMed_ACTIVE_ELEMENT_TOKEN";

  const SELECTION_CHANGE_TOKEN = "__SmartMed_SELECTION_CHANGE_TOKEN";

  exports.ACTIVE_ELEMENT_TOKEN = ACTIVE_ELEMENT_TOKEN;
  exports.CONTROL_ACCESSOR_TOKEN = CONTROL_ACCESSOR_TOKEN;
  exports.EVENT_TUNNEL_PROGRESS_TOKEN = EVENT_TUNNEL_PROGRESS_TOKEN;
  exports.EVENT_TUNNEL_TOKEN = EVENT_TUNNEL_TOKEN;
  exports.MODEL_MODIFIERS_TOKEN = MODEL_MODIFIERS_TOKEN;
  exports.SELECTION_CHANGE_TOKEN = SELECTION_CHANGE_TOKEN;
  exports.VALIDATION_ERRORS_TOKEN = VALIDATION_ERRORS_TOKEN;

  Object.defineProperty(exports, '__esModule', { value: true });

  return exports;

})({});
